# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Open Weather' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Open Weather
  pod 'Alamofire', '~> 4.7'

  target 'Open WeatherTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Open WeatherUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
